server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: "never"
